<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerW6liowq\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerW6liowq/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerW6liowq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerW6liowq\appDevDebugProjectContainer();
